name: Publish VS Code Extension

on:
  push:
    branches: [ "main" ]  # 主分支推送时触发
  workflow_dispatch:      # 允许手动触发

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Install standard-version
        run: npm install --save-dev standard-version

      - name: Set Git user name and email
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run standard-version
        run: npx standard-version  # 自动更新版本号

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package Extension
        run: vsce package  # 生成 .vsix 文件

      - name: Publish to Marketplace
        uses: HaaLeo/publish-vscode-extension@v1.6.2  # 第三方 Action 简化发布
        with:
          pat: ${{ secrets.SHELLING }}  # 引用 GitHub Secret
          registryUrl: https://marketplace.visualstudio.com
          skipDuplicate: true  # 忽略重复版本错误
